name: yarn test
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: void:deploy
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test
      - name: lint
        uses: borales/actions-yarn@v4
        with:
          cmd: format:fix
